### ISSUE TITLE
Establish markdown standard

### ISSUE THREAD

**Issue by Zk2u** [labs3/standards#2]

**Comment by 314159265359879** [comment]
I guess we should use this "Github flavoured Markdown" reference for our own standard?

https://github.github.com/gfm/

I have been using notion.so to go from word --> notion --> markdown not sure about the differences between the notion export and the github flavoured markdown. 

It would also be helpful if the standard specifies a default folder for images for example */img/example.png

**Comment by Zk2u** [comment]
i think so. i've attached something that will expand on these below that we can use. it also has implementation in VSCode.
[L3S-03 draft.md](https://github.com/labs3/standards/files/6380433/L3S-03.draft.md)
